name: CI

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Check imports
        run: uv run python -c "import app; import src.ingestion; import src.preprocessing; import src.training; import src.prediction; import src.evaluation"


      - name: Build Docker image
        run: docker build -t telco-churn-api .
